[pytest]
markers =
    integration: Testes de integração com LocalStack
    performance: Testes de performance
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*